### ISSUE TITLE
[iOS 16 branch] Unable to add img4 tags to request

### ISSUE THREAD

**Issue by UInt2048** [DanTheMann15/tsschecker#28]
I managed to compile the iOS 16 branch of the tool, but ran into this error trying to use it:

![image](https://user-images.githubusercontent.com/46784000/192143293-ee049db4-de83-43d5-9e37-4e96d57e8004.png)

**Comment by DanTheMann15** [comment]
Recompile the latest git commit, i just mitigated it.

see 6044c9c

**Comment by UInt2048** [comment]
Okay, the original error is gone, but now it's replaced by an unhandled 456 status code:

```
wrls10-8-13-117:tsschecker matthewbenedict$ tsschecker -d iPhone15,2 -B D73AP -e 1135916207521822 --generator 0xb9eba0abbf282205 --apnonce b81d392f059ddf0769c19352b67a3f25db1c27781f98b371df54be17ad4f743c -s --save-path ~/Blobs -i 16.0.1
tsschecker version: 0.351.0-6044c9ca06262ef0a27b6e1857f5861f50f543c4-RELEASE
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] User manually specified generator "0xb9eba0abbf282205"
[TSSC] User manually specified ECID to use, parsed "1135916207521822" to dec:1135916207521822 hex:4091c1a0b401e
[TSSC] User manually specified apnonce to use, parsed "b81d392f059ddf0769c19352b67a3f25db1c27781f98b371df54be17ad4f743c" to hex:b81d392f059ddf0769c19352b67a3f25db1c27781f98b371df54be17ad4f743c
```

![image](https://user-images.githubusercontent.com/46784000/192271785-7ce48228-dffb-40ea-9b49-bb74ad71fdad.png)

**Comment by DanTheMann15** [comment]
this seems to happen only on the iPhone 14 Pro models, this error is also similar to error 128 on A7/A8 devices, so i ignored the error in 78f4523 until i can find out more.

you should be able to save usable tickets on the iPhone 14 Pro/Max at this point, but we won't know for sure until futurerestore/idevicerestore gets updated to handle the iPhone 14 Pro models.

**Comment by UInt2048** [comment]
What am I doing wrong?

Also, I was confused by your comment in that commit. How is this a no-nonce request if I'm passing an APNonce parameter?

![image](https://user-images.githubusercontent.com/46784000/192395609-e8623ac5-8722-46ce-96bf-30ae633fca8f.png)

**Comment by DanTheMann15** [comment]
Try creating the "Blobs" folder before saving your shsh blobs, as far as i know tsschecker does not create the folder for you.

i can say thats another issue in itself.

as for noNonce requests, when you save blobs with tsschecker, it'll try to save 3 aptickets "Erase", "Update" and "Erase noNonce"

The first two tickets are requested with the ApNonce you specified, the third is requested without an ApNonce.

blobs without a nonce are sometimes used in cases such as a glitch with iOS 9 allowing restores if your blob didn't contain a nonce on some devices. so tsschecker was programmed to save two tickets with a nonce and one without.
