### ISSUE TITLE
Can you create a tsschecker release for Mac? I can't compile on my old intel Mac :(

### ISSUE THREAD

**Issue by metaljay** [DanTheMann15/tsschecker#34]
As title please haha :)

**Comment by DanTheMann15** [comment]
i can't compile for mac since i don't have one. :/

i could however, try to get a ci that'll build a static binary for macOS but i will be unable to test it.

**Comment by metaljay** [comment]
> i can't compile for mac since i don't have one. :/
> 
> i could however, try to get a ci that'll build a static binary for macOS but i will be unable to test it.

All good, I setup a windows VM and ran it natively. I’ll close this request 😁
